### ISSUE TITLE
Unhandled Promise Rejection TypeError: Expected value to be a number

### ISSUE THREAD

**Issue by CHMEX** [lukechilds/hyperdex#342]
During a SWAP I has presented with the following error

Unhandled Promise Rejection
TypeError: Expected value to be a number
    at round (app://-/bundle.js:19874:9)
    at _formatSwap (app://-/bundle.js:89960:73)
    at Array.map (<anonymous>)
    at app://-/bundle.js:90069:20
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:89859:191)
    at app://-/bundle.js:89859:361
    at <anonymous>

after closing the HyperDEX and reopening I can login but I'm instantly presented with the same error.
The Trading History appears empty.
Let me know if you need specifics  ( and how to get you useful information )

---

HyperDEX 0.1.0-alpha.5
Electron 2.0.2
win32 10.0.16299
Locale: en-US

**Comment by sindresorhus** [comment]
Sorry, it seems you were unlucky and downloaded alpha-4 (before we pulled it) which contained a bug regarding saving the some of the swap numbers as strings instead of numbers. You need to clear out your swap history to fix this. You can do that in the DevTools window, by going to "Application" tab and then click "Clear site data" in the "Clear storage" sidebar view.

**Comment by jansako** [comment]
I downloaded the latest today, got the same error. 

I did a few failed swaps, then error.

https://github.com/lukechilds/hyperdex/issues/348

**Comment by lukechilds** [comment]
It looks like any swaps made while the bug existed in the nightly or alpha-4 will have corrupted your swap database.

Can you try running this in the console:

```js
_swapDB._getAllSwapData().then(swaps => swaps.filter(swap => typeof swap.request.total === 'string').forEach(swap => _swapDB.db.remove(swap)))
```

It should remove *only* the corrupt swaps from your database and allow the app to function normally. Let me know if it works.

**Comment by lukechilds** [comment]
Hmmn, it looks this issue is still occurring sporadically. Sometimes swap values are treated as a number other times as a string.

We're looking into it.
