### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by jansako** [lukechilds/hyperdex#348]
HyperDEX 0.1.0-alpha.5
Electron 2.0.2
win32 10.0.17134
Locale: en-GB

Got this today when submitting a small trade:
![screenshot 29](https://user-images.githubusercontent.com/34211887/41170432-2e615132-6b01-11e8-9687-d823bfb40960.jpg)

Unhandled Promise Rejection
TypeError: Expected value to be a number
    at round (app://-/bundle.js:19874:9)
    at _formatSwap (app://-/bundle.js:89960:73)
    at Array.map (<anonymous>)
    at app://-/bundle.js:90069:20
    at Generator.next (<anonymous>)
    at step (app://-/bundle.js:89859:191)
    at app://-/bundle.js:89859:361
    at <anonymous>

I accidentally closed the whole app when I was trying to toggle to the console, sorry!

---

**Comment by jansako** [comment]
I see this is a duplicate. closing.
